### PR TITLE
Final changes

### PR DESCRIPTION
**Pull request by Usagib**
Opening pull request for lintern check

### CODE REVIEW

**Comment by Usagib** [comment]
Hello Team!
Just finished this first version of the project
used gradient to mimic the apple menu and also some backgrounf work with sprites :)
already passed W3Validation and correcter stickler stylelint errors.
waiting for code review
Happy Coding!

**Review by stratospherique — COMMENTED** [review]
### Pull request under the review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
## Great Work @Usagib  :sunglasses: . You're almost done :clap: . However, two requirements prevent us from approve your project:

#### Bottom

* [ ] It contains four elements which are links (to another articles or `#`). You should wrap your `img` inside `a` element to make them as links.

* [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload.

### That's it. When finished implementing the above, kindly resubmit another code review request. Keep UP the good work :muscle: :muscle: .

**Comment by Usagib** [comment]
Hello Team!
Finished implementing the changes!
Wainting for code review
Happy coding!

**Comment by samgaco** [comment]
#### Good job @Usagib :clap: It is approved! Congratulations on completing your first solo project :1st_place_medal: 

##### You can merge now to the master branch and submit the project completion form : D 

Regards!! :muscle:

**Pull request merged**
